name = "Aion-Str-Util"

# badges = ["github-actions/test.yml"]
authority="cpan:DART"
module_maker="ModuleBuildTiny"
static_install = "auto"

[release]
do_not_upload_to_cpan=false
hooks=[
    "cp lib/Aion/Str/Util.md README.md"
]
